// Code generated by MockGen. DO NOT EDIT.
// Source: issue_provider_product_contract_test.go

// Package scanner is a generated GoMock package.
package scanner

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	snyk "github.com/snyk/snyk-ls/domain/snyk"
	product "github.com/snyk/snyk-ls/internal/product"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockIssueProviderProductScanner is a mock of IssueProviderProductScanner interface.
type MockIssueProviderProductScanner struct {
	ctrl     *gomock.Controller
	recorder *MockIssueProviderProductScannerMockRecorder
}

// MockIssueProviderProductScannerMockRecorder is the mock recorder for MockIssueProviderProductScanner.
type MockIssueProviderProductScannerMockRecorder struct {
	mock *MockIssueProviderProductScanner
}

// NewMockIssueProviderProductScanner creates a new mock instance.
func NewMockIssueProviderProductScanner(ctrl *gomock.Controller) *MockIssueProviderProductScanner {
	mock := &MockIssueProviderProductScanner{ctrl: ctrl}
	mock.recorder = &MockIssueProviderProductScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueProviderProductScanner) EXPECT() *MockIssueProviderProductScannerMockRecorder {
	return m.recorder
}

// IsEnabledForFolder mocks base method.
func (m *MockIssueProviderProductScanner) IsEnabledForFolder(folderConfig *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabledForFolder", folderConfig)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabledForFolder indicates an expected call of IsEnabledForFolder.
func (mr *MockIssueProviderProductScannerMockRecorder) IsEnabledForFolder(folderConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabledForFolder", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).IsEnabledForFolder), folderConfig)
}

// Issue mocks base method.
func (m *MockIssueProviderProductScanner) Issue(key string) types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", key)
	ret0, _ := ret[0].(types.Issue)
	return ret0
}

// Issue indicates an expected call of Issue.
func (mr *MockIssueProviderProductScannerMockRecorder) Issue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).Issue), key)
}

// Issues mocks base method.
func (m *MockIssueProviderProductScanner) Issues() snyk.IssuesByFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issues")
	ret0, _ := ret[0].(snyk.IssuesByFile)
	return ret0
}

// Issues indicates an expected call of Issues.
func (mr *MockIssueProviderProductScannerMockRecorder) Issues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issues", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).Issues))
}

// IssuesForFile mocks base method.
func (m *MockIssueProviderProductScanner) IssuesForFile(path types.FilePath) []types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuesForFile", path)
	ret0, _ := ret[0].([]types.Issue)
	return ret0
}

// IssuesForFile indicates an expected call of IssuesForFile.
func (mr *MockIssueProviderProductScannerMockRecorder) IssuesForFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuesForFile", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).IssuesForFile), path)
}

// IssuesForRange mocks base method.
func (m *MockIssueProviderProductScanner) IssuesForRange(path types.FilePath, r types.Range) []types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuesForRange", path, r)
	ret0, _ := ret[0].([]types.Issue)
	return ret0
}

// IssuesForRange indicates an expected call of IssuesForRange.
func (mr *MockIssueProviderProductScannerMockRecorder) IssuesForRange(path, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuesForRange", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).IssuesForRange), path, r)
}

// Product mocks base method.
func (m *MockIssueProviderProductScanner) Product() product.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product")
	ret0, _ := ret[0].(product.Product)
	return ret0
}

// Product indicates an expected call of Product.
func (mr *MockIssueProviderProductScannerMockRecorder) Product() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).Product))
}

// Scan mocks base method.
func (m *MockIssueProviderProductScanner) Scan(ctx context.Context, pathToScan types.FilePath) ([]types.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, pathToScan)
	ret0, _ := ret[0].([]types.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockIssueProviderProductScannerMockRecorder) Scan(ctx, pathToScan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockIssueProviderProductScanner)(nil).Scan), ctx, pathToScan)
}
