linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - govet

linters-settings:
  goimports:
    local-prefixes: github.com/snyk/snyk-lsp

output:
  format: tab

run:
  deadline: 10m
