run:
  build-tags:
    - integration
  concurrency: 4
  issues-exit-code: 1
  tests: true
  timeout: 5m

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-calls: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  gofumpt:
    module-path: github.com/snyk/snyk-ls
    extra-rules: true
  goimports:
    local-prefixes: github.com/snyk/snyk-ls
  gosimple:
    checks: ['all']
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 160
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  promlinter:
    strict: true
  revive:
    rules:
      - name: blank-imports
        disabled: true
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
        disabled: true
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks: ['all']
  stylecheck:
    checks: ['all']
    http-status-code-whitelist: []

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # TODO(containedctx): revisit!
    #- containedctx
    # TODO(contextcheck): revisit
    #- contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    # TODO(goconst): revisit
    #- goconst
    # TODO(gocritic): revisit
    #- gocritic
    - gocyclo
    # TODO(godot): revisit
    #- godot
    # TODO(gofumpt): revisit
    #- gofumpt
    # TODO(goimports): revisit
    - goimports
    - goprintffuncname
    # TODO(gosec): revisit; consequences of revoking non-owner file permissions?
    #- gosec
    # TODO(interfacebloat): revisit in a followup; will require a breaking API change
    #- interfacebloat
    # TODO(ireturn): revisit in a followup; will require a breaking API change
    #- ireturn
    # TODO(lll): revisit in followup; formatting
    #- lll
    - misspell
    - nakedret
    # TODO(nestif): revisit in a followup; refactor will need more careful review
    #- nestif
    # TODO(nilerr): revisit; some tricky inversion of err in tests
    #- nilerr
    # TODO(nilnil): revisit
    #- nilnil
    # TODO(noctx): revisit in a followup; context lifecycle consequences and/or breaking API change
    #- noctx
    - nolintlint
    # TODO(prealloc): revisit in a followup; some logic around slices are ignoring errors
    #- prealloc
    - predeclared
    - promlinter
    # TODO(revive): revisit in a followup; extensive changes, some breaking. godoc requirement would be good to introduce
    # - revive
    - rowserrcheck
    - sqlclosecheck
    # TODO(stylecheck): revisit in a followup; some breaking API changes
    #- stylecheck
    - thelper
    - tparallel
    - unconvert
    # TODO(unparam): revisit
    #- unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    # TODO(wrapcheck): wrap errors in a followup
    #- wrapcheck

issues:
  exclude-dirs:
    - "docs"
    - "licenses"
    - "pact"
    - "ampli"
    - ".bin"
    - ".github"
    - ".vscode"
    - "build"

  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - forcetypeassert
        - goconst
        - ireturn
    - path: test/
      linters:
        - testpackage
    - path: \.go
      # TODO: remove this soon; unchecked errors are BAD
      linters:
        - errcheck
  include:
    - EXC0012
    - EXC0014
