linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - govet
    - gocyclo
    - dupl
    - errchkjson
    - exhaustive
    - gocognit
    - goconst
    - tenv

linters-settings:
  goimports:
    local-prefixes: github.com/snyk/snyk-ls

output:
  format: tab

run:
  deadline: 10m
