# Copyright 2022 Snyk Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet
    - gocyclo
    - dupl
    - errchkjson
    - exhaustive
    - gocognit
    - goconst
    - tenv

linters-settings:
  goimports:
    local-prefixes: github.com/snyk/snyk-ls
  exhaustive:
    default-signifies-exhaustive: true

output:
  format: tab

run:
  deadline: 10m
  skip-dirs:
    - "docs"
