version: '2'
run:
  build-tags:
    - integration
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      ignore-calls: false
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 160
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    promlinter:
      strict: true
    revive:
      rules:
        - name: blank-imports
          disabled: true
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
          disabled: true
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -ST1000 # Disable package comment enforcement
        - -ST1003 # Disable naming convention checks (e.g. myId -> myID)
      http-status-code-whitelist: [] # Flag ALL hard-coded HTTP status codes
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # TODO(containedctx): revisit!
    #- containedctx
    # TODO(contextcheck): revisit
    #- contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    # TODO(goconst): revisit
    #- goconst
    # TODO(gocritic): revisit
    #- gocritic
    - gocyclo
    # TODO(godot): revisit
    #- godot
    - goprintffuncname
    # TODO(gosec): revisit; consequences of revoking non-owner file permissions?
    #- gosec
    # TODO(interfacebloat): revisit in a followup; will require a breaking API change
    #- interfacebloat
    # TODO(ireturn): revisit in a followup; will require a breaking API change
    #- ireturn
    # TODO(lll): revisit in followup; formatting
    #- lll
    - misspell
    - nakedret
    # TODO(nestif): revisit in a followup; refactor will need more careful review
    #- nestif
    # TODO(nilerr): revisit; some tricky inversion of err in tests
    #- nilerr
    # TODO(nilnil): revisit
    #- nilnil
    # TODO(noctx): revisit in a followup; context lifecycle consequences and/or breaking API change
    #- noctx
    - nolintlint
    # TODO(prealloc): revisit in a followup; some logic around slices are ignoring errors
    #- prealloc
    - predeclared
    - promlinter
    # TODO(revive): revisit in a followup; extensive changes, some breaking. godoc requirement would be good to introduce
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # NOTE: removed tagliatelle as it conflicts too much with existing API wireformats
    # TODO(testpackage): improve open vs closed-box testing in a followup
    #- testpackage
    - thelper
    - tparallel
    - unconvert
    # TODO(unparam): revisit
    #- unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    # TODO(wrapcheck): wrap errors in a followup
    #- wrapcheck
  exclusions:
    paths:
      - docs
      - licenses
      - pact
      - ampli
      - .bin
      - .github
      - .vscode
      - build
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - forcetypeassert
          - goconst
          - ireturn
      - path: test/
        linters:
          - testpackage
      - path: \.go
        # TODO: remove this soon; unchecked errors are BAD
        linters:
          - errcheck
formatters:
  enable:
    - goimports
    # TODO(gofumpt): revisit
    #- gofumpt
  settings:
    gofumpt:
      module-path: github.com/snyk/snyk-ls
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/snyk/snyk-ls
  exclusions:
    paths:
      - docs
      - licenses
      - pact
      - ampli
      - .bin
      - .github
      - .vscode
      - build
