project_name: "snyk-lsp"

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    - go mod tidy

blobs:
  - provider: S3
    region: ${{ env.AWS_REGION }}
    bucket: ${{ env.AWS_S3_BUCKET_NAME }}
    ids:
      - "{{ .ProjectName }}"
    extra_files:
      - glob: "build/{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
      - glob: "build/metadata.json"
    folder: "{{ .ProjectName }}/"

builds:
  - flags:
      - -trimpath
    goarch:
      - "386"
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goarch: "386"
        goos: darwin
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.gitinfo={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - upx -9fv --lzma "{{ .Path }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256


dist: build

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
