project_name: "snyk-ls"
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    - go mod tidy

blobs:
  - provider: S3
    region: "{{ .Env.AWS_REGION }}"
    bucket: "{{ .Env.AWS_S3_BUCKET_NAME }}"

    extra_files:
      - glob: "build/{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
      - glob: "build/metadata.json"
    folder: "{{ .ProjectName }}/{{ .Env.LS_PROTOCOL_VERSION }}/"

builds:
  - flags:
      - -trimpath
    goarch:
      - "386"
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goarch: "386"
        goos: darwin
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X github.com/snyk/snyk-ls/application/config.Version={{.Version}} -X github.com/snyk/snyk-ls/application/config.LsProtocolVersion={{.Env.LS_PROTOCOL_VERSION}} -X 'github.com/snyk/snyk-ls/application/config.Development=false'
    mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

dist: build

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - LS_PROTOCOL_VERSION=2
