// Code generated by MockGen. DO NOT EDIT.
// Source: inline_value.go

// Package mock_snyk is a generated GoMock package.
package mock_snyk

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	snyk "github.com/snyk/snyk-ls/domain/snyk"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockInlineValue is a mock of InlineValue interface.
type MockInlineValue struct {
	ctrl     *gomock.Controller
	recorder *MockInlineValueMockRecorder
}

// MockInlineValueMockRecorder is the mock recorder for MockInlineValue.
type MockInlineValueMockRecorder struct {
	mock *MockInlineValue
}

// NewMockInlineValue creates a new mock instance.
func NewMockInlineValue(ctrl *gomock.Controller) *MockInlineValue {
	mock := &MockInlineValue{ctrl: ctrl}
	mock.recorder = &MockInlineValueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInlineValue) EXPECT() *MockInlineValueMockRecorder {
	return m.recorder
}

// Path mocks base method.
func (m *MockInlineValue) Path() types.FilePath {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(types.FilePath)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockInlineValueMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockInlineValue)(nil).Path))
}

// Range mocks base method.
func (m *MockInlineValue) Range() types.Range {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(types.Range)
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockInlineValueMockRecorder) Range() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockInlineValue)(nil).Range))
}

// String mocks base method.
func (m *MockInlineValue) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockInlineValueMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockInlineValue)(nil).String))
}

// Text mocks base method.
func (m *MockInlineValue) Text() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	return ret0
}

// Text indicates an expected call of Text.
func (mr *MockInlineValueMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockInlineValue)(nil).Text))
}

// MockInlineValueProvider is a mock of InlineValueProvider interface.
type MockInlineValueProvider struct {
	ctrl     *gomock.Controller
	recorder *MockInlineValueProviderMockRecorder
}

// MockInlineValueProviderMockRecorder is the mock recorder for MockInlineValueProvider.
type MockInlineValueProviderMockRecorder struct {
	mock *MockInlineValueProvider
}

// NewMockInlineValueProvider creates a new mock instance.
func NewMockInlineValueProvider(ctrl *gomock.Controller) *MockInlineValueProvider {
	mock := &MockInlineValueProvider{ctrl: ctrl}
	mock.recorder = &MockInlineValueProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInlineValueProvider) EXPECT() *MockInlineValueProviderMockRecorder {
	return m.recorder
}

// ClearInlineValues mocks base method.
func (m *MockInlineValueProvider) ClearInlineValues(path types.FilePath) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearInlineValues", path)
}

// ClearInlineValues indicates an expected call of ClearInlineValues.
func (mr *MockInlineValueProviderMockRecorder) ClearInlineValues(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearInlineValues", reflect.TypeOf((*MockInlineValueProvider)(nil).ClearInlineValues), path)
}

// GetInlineValues mocks base method.
func (m *MockInlineValueProvider) GetInlineValues(path types.FilePath, myRange types.Range) ([]snyk.InlineValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInlineValues", path, myRange)
	ret0, _ := ret[0].([]snyk.InlineValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInlineValues indicates an expected call of GetInlineValues.
func (mr *MockInlineValueProviderMockRecorder) GetInlineValues(path, myRange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInlineValues", reflect.TypeOf((*MockInlineValueProvider)(nil).GetInlineValues), path, myRange)
}
