// Code generated by MockGen. DO NOT EDIT.
// Source: summary_emitter.go

// Package scanstates is a generated GoMock package.
package scanstates

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScanStateChangeEmitter is a mock of ScanStateChangeEmitter interface.
type MockScanStateChangeEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockScanStateChangeEmitterMockRecorder
}

// MockScanStateChangeEmitterMockRecorder is the mock recorder for MockScanStateChangeEmitter.
type MockScanStateChangeEmitterMockRecorder struct {
	mock *MockScanStateChangeEmitter
}

// NewMockScanStateChangeEmitter creates a new mock instance.
func NewMockScanStateChangeEmitter(ctrl *gomock.Controller) *MockScanStateChangeEmitter {
	mock := &MockScanStateChangeEmitter{ctrl: ctrl}
	mock.recorder = &MockScanStateChangeEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanStateChangeEmitter) EXPECT() *MockScanStateChangeEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockScanStateChangeEmitter) Emit(aggregator StateSnapshot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", aggregator)
}

// Emit indicates an expected call of Emit.
func (mr *MockScanStateChangeEmitterMockRecorder) Emit(aggregator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockScanStateChangeEmitter)(nil).Emit), aggregator)
}
