// ABOUTME: Shared test helper that builds a JSDOM environment from the full rendered
// ABOUTME: production HTML fixture (scripts embedded in the same order as config.html).

import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Builds a fully-initialized JSDOM environment from the production HTML fixture.
 * The fixture is generated by: go run scripts/config-dialog/main.go -no-panel
 * Initial field values are set before the window load event fires so the dirty tracker
 * captures them as the baseline.
 *
 * @param {object} [options]
 * @param {string} [options.initialToken=""]
 * @param {string} [options.initialAuthMethod="oauth"]
 * @param {string} [options.initialEndpoint="https://api.snyk.io"]
 * @returns {Promise<Window>}
 */
export async function buildDom({
  initialToken = "",
  initialAuthMethod = "oauth",
  initialEndpoint = "https://api.snyk.io",
} = {}) {
  const html = await readFile(join(__dirname, "fixtures", "config-page.html"), "utf8");
  const dom = new JSDOM(html, { runScripts: "dangerously" });
  const win = dom.window;

  // Set initial values before the window load event fires so the dirty tracker
  // captures them as the baseline state.
  win.document.getElementById("token").value = initialToken;
  win.document.getElementById("authenticationMethod").value = initialAuthMethod;
  win.document.getElementById("endpoint").value = initialEndpoint;

  // Yield to the event loop so JSDOM can fire the window 'load' event, which
  // triggers app.js initialization (dirtyTracker, validation listeners, etc.).
  await new Promise((resolve) => win.setTimeout(resolve, 0));

  return win;
}
