// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/snyk-ls/internal/types (interfaces: ConfigResolverInterface)

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	configuration "github.com/snyk/go-application-framework/pkg/configuration"
	product "github.com/snyk/snyk-ls/internal/product"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockConfigResolverInterface is a mock of ConfigResolverInterface interface.
type MockConfigResolverInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigResolverInterfaceMockRecorder
}

// MockConfigResolverInterfaceMockRecorder is the mock recorder for MockConfigResolverInterface.
type MockConfigResolverInterfaceMockRecorder struct {
	mock *MockConfigResolverInterface
}

// NewMockConfigResolverInterface creates a new mock instance.
func NewMockConfigResolverInterface(ctrl *gomock.Controller) *MockConfigResolverInterface {
	mock := &MockConfigResolverInterface{ctrl: ctrl}
	mock.recorder = &MockConfigResolverInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigResolverInterface) EXPECT() *MockConfigResolverInterfaceMockRecorder {
	return m.recorder
}

// Configuration mocks base method.
func (m *MockConfigResolverInterface) Configuration() configuration.Configuration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Configuration")
	ret0, _ := ret[0].(configuration.Configuration)
	return ret0
}

// Configuration indicates an expected call of Configuration.
func (mr *MockConfigResolverInterfaceMockRecorder) Configuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configuration", reflect.TypeOf((*MockConfigResolverInterface)(nil).Configuration))
}

// DisplayableIssueTypesForFolder mocks base method.
func (m *MockConfigResolverInterface) DisplayableIssueTypesForFolder(arg0 *types.FolderConfig) map[product.FilterableIssueType]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayableIssueTypesForFolder", arg0)
	ret0, _ := ret[0].(map[product.FilterableIssueType]bool)
	return ret0
}

// DisplayableIssueTypesForFolder indicates an expected call of DisplayableIssueTypesForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) DisplayableIssueTypesForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayableIssueTypesForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).DisplayableIssueTypesForFolder), arg0)
}

// FilterSeverityForFolder mocks base method.
func (m *MockConfigResolverInterface) FilterSeverityForFolder(arg0 *types.FolderConfig) types.SeverityFilter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSeverityForFolder", arg0)
	ret0, _ := ret[0].(types.SeverityFilter)
	return ret0
}

// FilterSeverityForFolder indicates an expected call of FilterSeverityForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) FilterSeverityForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSeverityForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).FilterSeverityForFolder), arg0)
}

// GetBool mocks base method.
func (m *MockConfigResolverInterface) GetBool(arg0 string, arg1 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockConfigResolverInterfaceMockRecorder) GetBool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetBool), arg0, arg1)
}

// GetEffectiveValue mocks base method.
func (m *MockConfigResolverInterface) GetEffectiveValue(arg0 string, arg1 *types.FolderConfig) types.EffectiveValue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveValue", arg0, arg1)
	ret0, _ := ret[0].(types.EffectiveValue)
	return ret0
}

// GetEffectiveValue indicates an expected call of GetEffectiveValue.
func (mr *MockConfigResolverInterfaceMockRecorder) GetEffectiveValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveValue", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetEffectiveValue), arg0, arg1)
}

// GetInt mocks base method.
func (m *MockConfigResolverInterface) GetInt(arg0 string, arg1 *types.FolderConfig) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInt indicates an expected call of GetInt.
func (mr *MockConfigResolverInterfaceMockRecorder) GetInt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetInt), arg0, arg1)
}

// GetLDXSyncMachineConfig mocks base method.
func (m *MockConfigResolverInterface) GetLDXSyncMachineConfig() map[string]*types.LDXSyncField {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLDXSyncMachineConfig")
	ret0, _ := ret[0].(map[string]*types.LDXSyncField)
	return ret0
}

// GetLDXSyncMachineConfig indicates an expected call of GetLDXSyncMachineConfig.
func (mr *MockConfigResolverInterfaceMockRecorder) GetLDXSyncMachineConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLDXSyncMachineConfig", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetLDXSyncMachineConfig))
}

// GetSeverityFilter mocks base method.
func (m *MockConfigResolverInterface) GetSeverityFilter(arg0 string, arg1 *types.FolderConfig) *types.SeverityFilter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeverityFilter", arg0, arg1)
	ret0, _ := ret[0].(*types.SeverityFilter)
	return ret0
}

// GetSeverityFilter indicates an expected call of GetSeverityFilter.
func (mr *MockConfigResolverInterfaceMockRecorder) GetSeverityFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeverityFilter", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetSeverityFilter), arg0, arg1)
}

// GetStringSlice mocks base method.
func (m *MockConfigResolverInterface) GetStringSlice(arg0 string, arg1 *types.FolderConfig) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStringSlice", arg0, arg1)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetStringSlice indicates an expected call of GetStringSlice.
func (mr *MockConfigResolverInterfaceMockRecorder) GetStringSlice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringSlice", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetStringSlice), arg0, arg1)
}

// GetValue mocks base method.
func (m *MockConfigResolverInterface) GetValue(arg0 string, arg1 *types.FolderConfig) (interface{}, types.ConfigSource) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(types.ConfigSource)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockConfigResolverInterfaceMockRecorder) GetValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockConfigResolverInterface)(nil).GetValue), arg0, arg1)
}

// IsAutoScanEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsAutoScanEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAutoScanEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAutoScanEnabledForFolder indicates an expected call of IsAutoScanEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsAutoScanEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAutoScanEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsAutoScanEnabledForFolder), arg0)
}

// IsDeltaFindingsEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsDeltaFindingsEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeltaFindingsEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDeltaFindingsEnabledForFolder indicates an expected call of IsDeltaFindingsEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsDeltaFindingsEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeltaFindingsEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsDeltaFindingsEnabledForFolder), arg0)
}

// IsLocked mocks base method.
func (m *MockConfigResolverInterface) IsLocked(arg0 string, arg1 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockConfigResolverInterfaceMockRecorder) IsLocked(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsLocked), arg0, arg1)
}

// IsProductEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsProductEnabledForFolder(arg0 product.Product, arg1 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProductEnabledForFolder", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProductEnabledForFolder indicates an expected call of IsProductEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsProductEnabledForFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProductEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsProductEnabledForFolder), arg0, arg1)
}

// IsSnykCodeEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsSnykCodeEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSnykCodeEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSnykCodeEnabledForFolder indicates an expected call of IsSnykCodeEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsSnykCodeEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSnykCodeEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsSnykCodeEnabledForFolder), arg0)
}

// IsSnykIacEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsSnykIacEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSnykIacEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSnykIacEnabledForFolder indicates an expected call of IsSnykIacEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsSnykIacEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSnykIacEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsSnykIacEnabledForFolder), arg0)
}

// IsSnykOssEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsSnykOssEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSnykOssEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSnykOssEnabledForFolder indicates an expected call of IsSnykOssEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsSnykOssEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSnykOssEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsSnykOssEnabledForFolder), arg0)
}

// IsSnykSecretsEnabledForFolder mocks base method.
func (m *MockConfigResolverInterface) IsSnykSecretsEnabledForFolder(arg0 *types.FolderConfig) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSnykSecretsEnabledForFolder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSnykSecretsEnabledForFolder indicates an expected call of IsSnykSecretsEnabledForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IsSnykSecretsEnabledForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSnykSecretsEnabledForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IsSnykSecretsEnabledForFolder), arg0)
}

// IssueViewOptionsForFolder mocks base method.
func (m *MockConfigResolverInterface) IssueViewOptionsForFolder(arg0 *types.FolderConfig) types.IssueViewOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueViewOptionsForFolder", arg0)
	ret0, _ := ret[0].(types.IssueViewOptions)
	return ret0
}

// IssueViewOptionsForFolder indicates an expected call of IssueViewOptionsForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) IssueViewOptionsForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueViewOptionsForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).IssueViewOptionsForFolder), arg0)
}

// RiskScoreThresholdForFolder mocks base method.
func (m *MockConfigResolverInterface) RiskScoreThresholdForFolder(arg0 *types.FolderConfig) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RiskScoreThresholdForFolder", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// RiskScoreThresholdForFolder indicates an expected call of RiskScoreThresholdForFolder.
func (mr *MockConfigResolverInterfaceMockRecorder) RiskScoreThresholdForFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RiskScoreThresholdForFolder", reflect.TypeOf((*MockConfigResolverInterface)(nil).RiskScoreThresholdForFolder), arg0)
}

// SetLDXSyncCache mocks base method.
func (m *MockConfigResolverInterface) SetLDXSyncCache(arg0 *types.LDXSyncConfigCache) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLDXSyncCache", arg0)
}

// SetLDXSyncCache indicates an expected call of SetLDXSyncCache.
func (mr *MockConfigResolverInterfaceMockRecorder) SetLDXSyncCache(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLDXSyncCache", reflect.TypeOf((*MockConfigResolverInterface)(nil).SetLDXSyncCache), arg0)
}

// SetLDXSyncMachineConfig mocks base method.
func (m *MockConfigResolverInterface) SetLDXSyncMachineConfig(arg0 map[string]*types.LDXSyncField) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLDXSyncMachineConfig", arg0)
}

// SetLDXSyncMachineConfig indicates an expected call of SetLDXSyncMachineConfig.
func (mr *MockConfigResolverInterfaceMockRecorder) SetLDXSyncMachineConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLDXSyncMachineConfig", reflect.TypeOf((*MockConfigResolverInterface)(nil).SetLDXSyncMachineConfig), arg0)
}
