// Code generated by MockGen. DO NOT EDIT.
// Source: scan.go

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	product "github.com/snyk/snyk-ls/internal/product"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockScanner is a mock of Scanner interface.
type MockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockScannerMockRecorder
}

// MockScannerMockRecorder is the mock recorder for MockScanner.
type MockScannerMockRecorder struct {
	mock *MockScanner
}

// NewMockScanner creates a new mock instance.
func NewMockScanner(ctrl *gomock.Controller) *MockScanner {
	mock := &MockScanner{ctrl: ctrl}
	mock.recorder = &MockScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanner) EXPECT() *MockScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockScanner) Scan(ctx context.Context, objectToScan types.FilePath, processResults types.ScanResultProcessor, workspaceFolderConfig *types.FolderConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Scan", ctx, objectToScan, processResults, workspaceFolderConfig)
}

// Scan indicates an expected call of Scan.
func (mr *MockScannerMockRecorder) Scan(ctx, objectToScan, processResults, workspaceFolderConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockScanner)(nil).Scan), ctx, objectToScan, processResults, workspaceFolderConfig)
}

// MockProductScanner is a mock of ProductScanner interface.
type MockProductScanner struct {
	ctrl     *gomock.Controller
	recorder *MockProductScannerMockRecorder
}

// MockProductScannerMockRecorder is the mock recorder for MockProductScanner.
type MockProductScannerMockRecorder struct {
	mock *MockProductScanner
}

// NewMockProductScanner creates a new mock instance.
func NewMockProductScanner(ctrl *gomock.Controller) *MockProductScanner {
	mock := &MockProductScanner{ctrl: ctrl}
	mock.recorder = &MockProductScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductScanner) EXPECT() *MockProductScannerMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockProductScanner) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockProductScannerMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockProductScanner)(nil).IsEnabled))
}

// Product mocks base method.
func (m *MockProductScanner) Product() product.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product")
	ret0, _ := ret[0].(product.Product)
	return ret0
}

// Product indicates an expected call of Product.
func (mr *MockProductScannerMockRecorder) Product() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockProductScanner)(nil).Product))
}

// Scan mocks base method.
func (m *MockProductScanner) Scan(ctx context.Context, objectToScan types.FilePath, workspaceFolderConfig *types.FolderConfig) ([]types.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, objectToScan, workspaceFolderConfig)
	ret0, _ := ret[0].([]types.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockProductScannerMockRecorder) Scan(ctx, objectToScan, workspaceFolderConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockProductScanner)(nil).Scan), ctx, objectToScan, workspaceFolderConfig)
}
