on: [push, pull_request]

name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22, 1.x]

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          go test ./...
          go test -race ./...

      - name: go vet
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
