// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_learn is a generated GoMock package.
package mock_learn

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAllLessons mocks base method.
func (m *MockService) GetAllLessons() ([]Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLessons")
	ret0, _ := ret[0].([]Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLessons indicates an expected call of GetAllLessons.
func (mr *MockServiceMockRecorder) GetAllLessons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLessons", reflect.TypeOf((*MockService)(nil).GetAllLessons))
}

// GetLesson mocks base method.
func (m *MockService) GetLesson(ecosystem, rule string, cwes, cves []string, issueType types.IssueType) (*Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLesson", ecosystem, rule, cwes, cves, issueType)
	ret0, _ := ret[0].(*Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLesson indicates an expected call of GetLesson.
func (mr *MockServiceMockRecorder) GetLesson(ecosystem, rule, cwes, cves, issueType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLesson", reflect.TypeOf((*MockService)(nil).GetLesson), ecosystem, rule, cwes, cves, issueType)
}

// LearnEndpoint mocks base method.
func (m *MockService) LearnEndpoint() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LearnEndpoint")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LearnEndpoint indicates an expected call of LearnEndpoint.
func (mr *MockServiceMockRecorder) LearnEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LearnEndpoint", reflect.TypeOf((*MockService)(nil).LearnEndpoint))
}

// MaintainCacheFunc mocks base method.
func (m *MockService) MaintainCacheFunc() func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaintainCacheFunc")
	ret0, _ := ret[0].(func())
	return ret0
}

// MaintainCacheFunc indicates an expected call of MaintainCacheFunc.
func (mr *MockServiceMockRecorder) MaintainCacheFunc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaintainCacheFunc", reflect.TypeOf((*MockService)(nil).MaintainCacheFunc))
}
