// Code generated by MockGen. DO NOT EDIT.
// Source: ldx_sync_service.go

// Package mock_command is a generated GoMock package.
package mock_command

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/snyk/snyk-ls/application/config"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockLdxSyncService is a mock of LdxSyncService interface.
type MockLdxSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockLdxSyncServiceMockRecorder
}

// MockLdxSyncServiceMockRecorder is the mock recorder for MockLdxSyncService.
type MockLdxSyncServiceMockRecorder struct {
	mock *MockLdxSyncService
}

// NewMockLdxSyncService creates a new mock instance.
func NewMockLdxSyncService(ctrl *gomock.Controller) *MockLdxSyncService {
	mock := &MockLdxSyncService{ctrl: ctrl}
	mock.recorder = &MockLdxSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLdxSyncService) EXPECT() *MockLdxSyncServiceMockRecorder {
	return m.recorder
}

// RefreshConfigFromLdxSync mocks base method.
func (m *MockLdxSyncService) RefreshConfigFromLdxSync(c *config.Config, workspaceFolders []types.Folder) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshConfigFromLdxSync", c, workspaceFolders)
}

// RefreshConfigFromLdxSync indicates an expected call of RefreshConfigFromLdxSync.
func (mr *MockLdxSyncServiceMockRecorder) RefreshConfigFromLdxSync(c, workspaceFolders interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshConfigFromLdxSync", reflect.TypeOf((*MockLdxSyncService)(nil).RefreshConfigFromLdxSync), c, workspaceFolders)
}
