// Code generated by MockGen. DO NOT EDIT.
// Source: ldx_sync_service.go

// Package mock_command is a generated GoMock package.
package mock_command

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zerolog "github.com/rs/zerolog"
	ldx_sync_config "github.com/snyk/go-application-framework/pkg/apiclients/ldx_sync_config"
	configuration "github.com/snyk/go-application-framework/pkg/configuration"
	workflow "github.com/snyk/go-application-framework/pkg/workflow"
	notification "github.com/snyk/snyk-ls/internal/notification"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockLdxSyncApiClient is a mock of LdxSyncApiClient interface.
type MockLdxSyncApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockLdxSyncApiClientMockRecorder
}

// MockLdxSyncApiClientMockRecorder is the mock recorder for MockLdxSyncApiClient.
type MockLdxSyncApiClientMockRecorder struct {
	mock *MockLdxSyncApiClient
}

// NewMockLdxSyncApiClient creates a new mock instance.
func NewMockLdxSyncApiClient(ctrl *gomock.Controller) *MockLdxSyncApiClient {
	mock := &MockLdxSyncApiClient{ctrl: ctrl}
	mock.recorder = &MockLdxSyncApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLdxSyncApiClient) EXPECT() *MockLdxSyncApiClientMockRecorder {
	return m.recorder
}

// GetUserConfigForProject mocks base method.
func (m *MockLdxSyncApiClient) GetUserConfigForProject(ctx context.Context, engine workflow.Engine, projectPath, userSelectedOrg string) ldx_sync_config.LdxSyncConfigResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserConfigForProject", ctx, engine, projectPath, userSelectedOrg)
	ret0, _ := ret[0].(ldx_sync_config.LdxSyncConfigResult)
	return ret0
}

// GetUserConfigForProject indicates an expected call of GetUserConfigForProject.
func (mr *MockLdxSyncApiClientMockRecorder) GetUserConfigForProject(ctx, engine, projectPath, userSelectedOrg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserConfigForProject", reflect.TypeOf((*MockLdxSyncApiClient)(nil).GetUserConfigForProject), ctx, engine, projectPath, userSelectedOrg)
}

// MockLdxSyncService is a mock of LdxSyncService interface.
type MockLdxSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockLdxSyncServiceMockRecorder
}

// MockLdxSyncServiceMockRecorder is the mock recorder for MockLdxSyncService.
type MockLdxSyncServiceMockRecorder struct {
	mock *MockLdxSyncService
}

// NewMockLdxSyncService creates a new mock instance.
func NewMockLdxSyncService(ctrl *gomock.Controller) *MockLdxSyncService {
	mock := &MockLdxSyncService{ctrl: ctrl}
	mock.recorder = &MockLdxSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLdxSyncService) EXPECT() *MockLdxSyncServiceMockRecorder {
	return m.recorder
}

// RefreshConfigFromLdxSync mocks base method.
func (m *MockLdxSyncService) RefreshConfigFromLdxSync(ctx context.Context, conf configuration.Configuration, engine workflow.Engine, logger *zerolog.Logger, workspaceFolders []types.Folder, notifier notification.Notifier) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshConfigFromLdxSync", ctx, conf, engine, logger, workspaceFolders, notifier)
}

// RefreshConfigFromLdxSync indicates an expected call of RefreshConfigFromLdxSync.
func (mr *MockLdxSyncServiceMockRecorder) RefreshConfigFromLdxSync(ctx, conf, engine, logger, workspaceFolders, notifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshConfigFromLdxSync", reflect.TypeOf((*MockLdxSyncService)(nil).RefreshConfigFromLdxSync), ctx, conf, engine, logger, workspaceFolders, notifier)
}
