name: 'Setup Go'
description: 'Determine Go version from go.mod and set up Go with caching'
runs:
  using: 'composite'
  steps:
    - name: Determine Go version
      shell: bash
      run: |
        sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: "true"
