// Code generated by MockGen. DO NOT EDIT.
// Source: git_persistence_provider.go

// Package mock_persistence is a generated GoMock package.
package mock_persistence

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	product "github.com/snyk/snyk-ls/internal/product"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockScanSnapshotPersister is a mock of ScanSnapshotPersister interface.
type MockScanSnapshotPersister struct {
	ctrl     *gomock.Controller
	recorder *MockScanSnapshotPersisterMockRecorder
}

// MockScanSnapshotPersisterMockRecorder is the mock recorder for MockScanSnapshotPersister.
type MockScanSnapshotPersisterMockRecorder struct {
	mock *MockScanSnapshotPersister
}

// NewMockScanSnapshotPersister creates a new mock instance.
func NewMockScanSnapshotPersister(ctrl *gomock.Controller) *MockScanSnapshotPersister {
	mock := &MockScanSnapshotPersister{ctrl: ctrl}
	mock.recorder = &MockScanSnapshotPersisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanSnapshotPersister) EXPECT() *MockScanSnapshotPersisterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockScanSnapshotPersister) Add(folderPath types.FilePath, commitHash string, issueList []types.Issue, p product.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", folderPath, commitHash, issueList, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockScanSnapshotPersisterMockRecorder) Add(folderPath, commitHash, issueList, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Add), folderPath, commitHash, issueList, p)
}

// Clear mocks base method.
func (m *MockScanSnapshotPersister) Clear(folderPath []types.FilePath, deleteOnlyExpired bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", folderPath, deleteOnlyExpired)
}

// Clear indicates an expected call of Clear.
func (mr *MockScanSnapshotPersisterMockRecorder) Clear(folderPath, deleteOnlyExpired interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Clear), folderPath, deleteOnlyExpired)
}

// ClearFolder mocks base method.
func (m *MockScanSnapshotPersister) ClearFolder(folderPath types.FilePath) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearFolder", folderPath)
}

// ClearFolder indicates an expected call of ClearFolder.
func (mr *MockScanSnapshotPersisterMockRecorder) ClearFolder(folderPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearFolder", reflect.TypeOf((*MockScanSnapshotPersister)(nil).ClearFolder), folderPath)
}

// Exists mocks base method.
func (m *MockScanSnapshotPersister) Exists(folderPath types.FilePath, commitHash string, p product.Product) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", folderPath, commitHash, p)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockScanSnapshotPersisterMockRecorder) Exists(folderPath, commitHash, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Exists), folderPath, commitHash, p)
}

// GetPersistedIssueList mocks base method.
func (m *MockScanSnapshotPersister) GetPersistedIssueList(folderPath types.FilePath, p product.Product) ([]types.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersistedIssueList", folderPath, p)
	ret0, _ := ret[0].([]types.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersistedIssueList indicates an expected call of GetPersistedIssueList.
func (mr *MockScanSnapshotPersisterMockRecorder) GetPersistedIssueList(folderPath, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersistedIssueList", reflect.TypeOf((*MockScanSnapshotPersister)(nil).GetPersistedIssueList), folderPath, p)
}

// Init mocks base method.
func (m *MockScanSnapshotPersister) Init(folderPath []types.FilePath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", folderPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockScanSnapshotPersisterMockRecorder) Init(folderPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Init), folderPath)
}
