// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/snyk-ls/domain/snyk/persistence (interfaces: ScanSnapshotPersister)

// Package mock_persistence is a generated GoMock package.
package mock_persistence

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	product "github.com/snyk/snyk-ls/internal/product"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockScanSnapshotPersister is a mock of ScanSnapshotPersister interface.
type MockScanSnapshotPersister struct {
	ctrl     *gomock.Controller
	recorder *MockScanSnapshotPersisterMockRecorder
}

// MockScanSnapshotPersisterMockRecorder is the mock recorder for MockScanSnapshotPersister.
type MockScanSnapshotPersisterMockRecorder struct {
	mock *MockScanSnapshotPersister
}

// NewMockScanSnapshotPersister creates a new mock instance.
func NewMockScanSnapshotPersister(ctrl *gomock.Controller) *MockScanSnapshotPersister {
	mock := &MockScanSnapshotPersister{ctrl: ctrl}
	mock.recorder = &MockScanSnapshotPersisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanSnapshotPersister) EXPECT() *MockScanSnapshotPersisterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockScanSnapshotPersister) Add(arg0 types.FilePath, arg1 string, arg2 []types.Issue, arg3 product.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockScanSnapshotPersisterMockRecorder) Add(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Add), arg0, arg1, arg2, arg3)
}

// CleanupCorruptedSnapshot mocks base method.
func (m *MockScanSnapshotPersister) CleanupCorruptedSnapshot(arg0 types.FilePath, arg1 product.Product) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupCorruptedSnapshot", arg0, arg1)
}

// CleanupCorruptedSnapshot indicates an expected call of CleanupCorruptedSnapshot.
func (mr *MockScanSnapshotPersisterMockRecorder) CleanupCorruptedSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupCorruptedSnapshot", reflect.TypeOf((*MockScanSnapshotPersister)(nil).CleanupCorruptedSnapshot), arg0, arg1)
}

// Clear mocks base method.
func (m *MockScanSnapshotPersister) Clear(arg0 []types.FilePath, arg1 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", arg0, arg1)
}

// Clear indicates an expected call of Clear.
func (mr *MockScanSnapshotPersisterMockRecorder) Clear(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Clear), arg0, arg1)
}

// ClearFolder mocks base method.
func (m *MockScanSnapshotPersister) ClearFolder(arg0 types.FilePath) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearFolder", arg0)
}

// ClearFolder indicates an expected call of ClearFolder.
func (mr *MockScanSnapshotPersisterMockRecorder) ClearFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearFolder", reflect.TypeOf((*MockScanSnapshotPersister)(nil).ClearFolder), arg0)
}

// Exists mocks base method.
func (m *MockScanSnapshotPersister) Exists(arg0 types.FilePath, arg1 string, arg2 product.Product) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockScanSnapshotPersisterMockRecorder) Exists(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Exists), arg0, arg1, arg2)
}

// GetPersistedIssueList mocks base method.
func (m *MockScanSnapshotPersister) GetPersistedIssueList(arg0 types.FilePath, arg1 product.Product) ([]types.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersistedIssueList", arg0, arg1)
	ret0, _ := ret[0].([]types.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersistedIssueList indicates an expected call of GetPersistedIssueList.
func (mr *MockScanSnapshotPersisterMockRecorder) GetPersistedIssueList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersistedIssueList", reflect.TypeOf((*MockScanSnapshotPersister)(nil).GetPersistedIssueList), arg0, arg1)
}

// Init mocks base method.
func (m *MockScanSnapshotPersister) Init(arg0 []types.FilePath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockScanSnapshotPersisterMockRecorder) Init(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockScanSnapshotPersister)(nil).Init), arg0)
}
