// Code generated by MockGen. DO NOT EDIT.
// Source: folder_issue_provider_contract_test.go

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	snyk "github.com/snyk/snyk-ls/domain/snyk"
	types "github.com/snyk/snyk-ls/internal/types"
)

// MockFolderIssueProviderScanner is a mock of FolderIssueProviderScanner interface.
type MockFolderIssueProviderScanner struct {
	ctrl     *gomock.Controller
	recorder *MockFolderIssueProviderScannerMockRecorder
}

// MockFolderIssueProviderScannerMockRecorder is the mock recorder for MockFolderIssueProviderScanner.
type MockFolderIssueProviderScannerMockRecorder struct {
	mock *MockFolderIssueProviderScanner
}

// NewMockFolderIssueProviderScanner creates a new mock instance.
func NewMockFolderIssueProviderScanner(ctrl *gomock.Controller) *MockFolderIssueProviderScanner {
	mock := &MockFolderIssueProviderScanner{ctrl: ctrl}
	mock.recorder = &MockFolderIssueProviderScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderIssueProviderScanner) EXPECT() *MockFolderIssueProviderScannerMockRecorder {
	return m.recorder
}

// Init mocks base method.
func (m *MockFolderIssueProviderScanner) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockFolderIssueProviderScannerMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).Init), ctx)
}

// Issue mocks base method.
func (m *MockFolderIssueProviderScanner) Issue(key string) types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", key)
	ret0, _ := ret[0].(types.Issue)
	return ret0
}

// Issue indicates an expected call of Issue.
func (mr *MockFolderIssueProviderScannerMockRecorder) Issue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).Issue), key)
}

// Issues mocks base method.
func (m *MockFolderIssueProviderScanner) Issues() snyk.IssuesByFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issues")
	ret0, _ := ret[0].(snyk.IssuesByFile)
	return ret0
}

// Issues indicates an expected call of Issues.
func (mr *MockFolderIssueProviderScannerMockRecorder) Issues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issues", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).Issues))
}

// IssuesForFile mocks base method.
func (m *MockFolderIssueProviderScanner) IssuesForFile(path types.FilePath) []types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuesForFile", path)
	ret0, _ := ret[0].([]types.Issue)
	return ret0
}

// IssuesForFile indicates an expected call of IssuesForFile.
func (mr *MockFolderIssueProviderScannerMockRecorder) IssuesForFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuesForFile", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).IssuesForFile), path)
}

// IssuesForRange mocks base method.
func (m *MockFolderIssueProviderScanner) IssuesForRange(path types.FilePath, r types.Range) []types.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuesForRange", path, r)
	ret0, _ := ret[0].([]types.Issue)
	return ret0
}

// IssuesForRange indicates an expected call of IssuesForRange.
func (mr *MockFolderIssueProviderScannerMockRecorder) IssuesForRange(path, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuesForRange", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).IssuesForRange), path, r)
}

// Scan mocks base method.
func (m *MockFolderIssueProviderScanner) Scan(ctx context.Context, pathToScan types.FilePath, processResults types.ScanResultProcessor, postActionFunc types.PostAction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Scan", ctx, pathToScan, processResults, postActionFunc)
}

// Scan indicates an expected call of Scan.
func (mr *MockFolderIssueProviderScannerMockRecorder) Scan(ctx, pathToScan, processResults, postActionFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockFolderIssueProviderScanner)(nil).Scan), ctx, pathToScan, processResults, postActionFunc)
}
